In [1]:
import numpy as np

## Question 1

In [4]:
print(np.__version__)

1.20.3


In [14]:
import pandas as pd

In [70]:
df = pd.read_csv('Desktop/mlzoomcamp/data_cars.csv')

## Question 2 

In [77]:
df.describe()

Year    Engine HP  Number of Doors   highway MPG      city mpg  \
count  11914.000000  11845.00000     11908.000000  11914.000000  11914.000000   
mean    2010.384338    249.38607         3.436093     26.637485     19.733255   
std        7.579740    109.19187         0.881315      8.863001      8.987798   
min     1990.000000     55.00000         2.000000     12.000000      7.000000   
25%     2007.000000    170.00000         2.000000     22.000000     16.000000   
50%     2015.000000    227.00000         4.000000     26.000000     18.000000   
75%     2016.000000    300.00000         4.000000     30.000000     22.000000   
max     2017.000000   1001.00000         4.000000    354.000000    137.000000   

         Popularity          MSRP  
count  11914.000000  1.191400e+04  
mean    1554.911197  4.059474e+04  
std     1441.855347  6.010910e+04  
min        2.000000  2.000000e+03  
25%      549.000000  2.100000e+04  
50%     1385.000000  2.999500e+04  
75%     2009.000000  4.223125e+04  
max     5657.000000  2.065902e+06

## Question 3

In [80]:
df['Make'].value_counts().sort_values(ascending = False)

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

## Question 4 

In [71]:
df[df['Make'] == 'Audi']['Model'].nunique()

34

## Question 5 

In [82]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

## Question 6

In [60]:
df['Engine Cylinders'].median()

6.0

In [61]:
df['Engine Cylinders'].value_counts().sort_values(ascending = False)

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [73]:
df['Engine Cylinders'].isna().sum()

30

In [74]:
df['Engine Cylinders'].fillna('4.0', inplace = True)

In [75]:
df['Engine Cylinders'].value_counts().sort_values(ascending = False)

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
4.0       30
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [76]:
df['Engine Cylinders'].median()

6.0

## Question 7 

In [110]:
X = np.array(df[df['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates(), dtype='float')

In [111]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [112]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [113]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [114]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [115]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [116]:
temp = XTX_inverse.dot(X.T)

In [117]:
w = temp.dot(y)

In [118]:
w

array([  4.59494481, -63.56432501])